### ISSUE TITLE
Cannot install from live ISO in VirtualBox

### ISSUE THREAD

**Issue by earthday** [cyberos/cyber-install-scripts#2]
I'm not sure this repo is a good place for this issue, if not, tell me, I can repost it to the correct repo.

I can use `curl` to get a response which proves the network is good, but the install told me `The system is not connected to the Internet.`

Is there any way or workaround to skip the network connection check?

![image](https://user-images.githubusercontent.com/90078/117921312-1c013300-b323-11eb-816a-369601f517a8.png)

**Comment by omaemae** [comment]
I don't know why that is the case, sorry :(

**Comment by omaemae** [comment]
i have no idea about VirtualBox, but does restarting the installer help?

**Comment by earthday** [comment]
Looks like the endpoint for the internet connection check is unstable for me, today I got lucky, and finished the install.

**Comment by earthday** [comment]
Thanks, @omaemae, I tried to restart, that is no help. As the above message, it's more like an unstable network issue.

Now, the problem is gone. Let me close this issue.

**Comment by omaemae** [comment]
glad you got it working :)
